/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractUniqueUtxo
 */
public class ContractUniqueUtxoTest {
    private final ContractUniqueUtxo model = new ContractUniqueUtxo();

    /**
     * Model tests for ContractUniqueUtxo
     */
    @Test
    public void testContractUniqueUtxo() {
        // TODO: test ContractUniqueUtxo
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'txIndex'
     */
    @Test
    public void txIndexTest() {
        // TODO: test txIndex
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'customData'
     */
    @Test
    public void customDataTest() {
        // TODO: test customData
    }

    /**
     * Test the property 'satoshi'
     */
    @Test
    public void satoshiTest() {
        // TODO: test satoshi
    }

    /**
     * Test the property 'satoshiString'
     */
    @Test
    public void satoshiStringTest() {
        // TODO: test satoshiString
    }

}
