/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractNftSellUtxo
 */
public class ContractNftSellUtxoTest {
    private final ContractNftSellUtxo model = new ContractNftSellUtxo();

    /**
     * Model tests for ContractNftSellUtxo
     */
    @Test
    public void testContractNftSellUtxo() {
        // TODO: test ContractNftSellUtxo
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'contractAddress'
     */
    @Test
    public void contractAddressTest() {
        // TODO: test contractAddress
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'txIndex'
     */
    @Test
    public void txIndexTest() {
        // TODO: test txIndex
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'tokenIndex'
     */
    @Test
    public void tokenIndexTest() {
        // TODO: test tokenIndex
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'satoshi'
     */
    @Test
    public void satoshiTest() {
        // TODO: test satoshi
    }

    /**
     * Test the property 'satoshiString'
     */
    @Test
    public void satoshiStringTest() {
        // TODO: test satoshiString
    }

    /**
     * Test the property 'height'
     */
    @Test
    public void heightTest() {
        // TODO: test height
    }

    /**
     * Test the property 'isReady'
     */
    @Test
    public void isReadyTest() {
        // TODO: test isReady
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'metaTxid'
     */
    @Test
    public void metaTxidTest() {
        // TODO: test metaTxid
    }

    /**
     * Test the property 'metaOutputIndex'
     */
    @Test
    public void metaOutputIndexTest() {
        // TODO: test metaOutputIndex
    }

    /**
     * Test the property 'tokenSupply'
     */
    @Test
    public void tokenSupplyTest() {
        // TODO: test tokenSupply
    }

    /**
     * Test the property 'flag'
     */
    @Test
    public void flagTest() {
        // TODO: test flag
    }

}
