/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractFtBalance
 */
public class ContractFtBalanceTest {
    private final ContractFtBalance model = new ContractFtBalance();

    /**
     * Model tests for ContractFtBalance
     */
    @Test
    public void testContractFtBalance() {
        // TODO: test ContractFtBalance
    }

    /**
     * Test the property 'codeHash'
     */
    @Test
    public void codeHashTest() {
        // TODO: test codeHash
    }

    /**
     * Test the property 'genesis'
     */
    @Test
    public void genesisTest() {
        // TODO: test genesis
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'symbol'
     */
    @Test
    public void symbolTest() {
        // TODO: test symbol
    }

    /**
     * Test the property 'decimal'
     */
    @Test
    public void decimalTest() {
        // TODO: test decimal
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'utxoCount'
     */
    @Test
    public void utxoCountTest() {
        // TODO: test utxoCount
    }

    /**
     * Test the property 'confirmed'
     */
    @Test
    public void confirmedTest() {
        // TODO: test confirmed
    }

    /**
     * Test the property 'confirmedString'
     */
    @Test
    public void confirmedStringTest() {
        // TODO: test confirmedString
    }

    /**
     * Test the property 'unconfirmed'
     */
    @Test
    public void unconfirmedTest() {
        // TODO: test unconfirmed
    }

    /**
     * Test the property 'unconfirmedString'
     */
    @Test
    public void unconfirmedStringTest() {
        // TODO: test unconfirmedString
    }

}
