/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ContractNftGenesisSummary
 */
public class ContractNftGenesisSummaryTest {
    private final ContractNftGenesisSummary model = new ContractNftGenesisSummary();

    /**
     * Model tests for ContractNftGenesisSummary
     */
    @Test
    public void testContractNftGenesisSummary() {
        // TODO: test ContractNftGenesisSummary
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

    /**
     * Test the property 'sensibleId'
     */
    @Test
    public void sensibleIdTest() {
        // TODO: test sensibleId
    }

    /**
     * Test the property 'metaTxid'
     */
    @Test
    public void metaTxidTest() {
        // TODO: test metaTxid
    }

    /**
     * Test the property 'metaOutputIndex'
     */
    @Test
    public void metaOutputIndexTest() {
        // TODO: test metaOutputIndex
    }

    /**
     * Test the property 'tokenSupply'
     */
    @Test
    public void tokenSupplyTest() {
        // TODO: test tokenSupply
    }

    /**
     * Test the property 'count'
     */
    @Test
    public void countTest() {
        // TODO: test count
    }

}
