/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.7
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.metasv.mvc.client.openapi.model.InvalidBroadcastCollide;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InvalidBroadCast
 */
public class InvalidBroadCastTest {
    private final InvalidBroadCast model = new InvalidBroadCast();

    /**
     * Model tests for InvalidBroadCast
     */
    @Test
    public void testInvalidBroadCast() {
        // TODO: test InvalidBroadCast
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'rejectCode'
     */
    @Test
    public void rejectCodeTest() {
        // TODO: test rejectCode
    }

    /**
     * Test the property 'rejectReason'
     */
    @Test
    public void rejectReasonTest() {
        // TODO: test rejectReason
    }

    /**
     * Test the property 'collideWith'
     */
    @Test
    public void collideWithTest() {
        // TODO: test collideWith
    }

}
