/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TreasuryHistory
 */
public class TreasuryHistoryTest {
    private final TreasuryHistory model = new TreasuryHistory();

    /**
     * Model tests for TreasuryHistory
     */
    @Test
    public void testTreasuryHistory() {
        // TODO: test TreasuryHistory
    }

    /**
     * Test the property 'txid'
     */
    @Test
    public void txidTest() {
        // TODO: test txid
    }

    /**
     * Test the property 'outcome'
     */
    @Test
    public void outcomeTest() {
        // TODO: test outcome
    }

    /**
     * Test the property 'timestamp'
     */
    @Test
    public void timestampTest() {
        // TODO: test timestamp
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'announcementUrl'
     */
    @Test
    public void announcementUrlTest() {
        // TODO: test announcementUrl
    }

}
