/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Tx simple info for block tx list.
 */
@ApiModel(description = "Tx simple info for block tx list.")
@JsonPropertyOrder({
  BlockTx.JSON_PROPERTY_TXID,
  BlockTx.JSON_PROPERTY_HEIGHT,
  BlockTx.JSON_PROPERTY_BLOCK_HASH,
  BlockTx.JSON_PROPERTY_SIZE,
  BlockTx.JSON_PROPERTY_INPUT_COUNT,
  BlockTx.JSON_PROPERTY_OUTPUT_COUNT,
  BlockTx.JSON_PROPERTY_LOCK_TIME,
  BlockTx.JSON_PROPERTY_FEE,
  BlockTx.JSON_PROPERTY_CONFIRMATIONS,
  BlockTx.JSON_PROPERTY_TIMESTAMP
})
@JsonTypeName("BlockTx")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-06T11:46:13.148624+09:00[Asia/Tokyo]")
public class BlockTx {
  public static final String JSON_PROPERTY_TXID = "txid";
  private String txid;

  public static final String JSON_PROPERTY_HEIGHT = "height";
  private Long height;

  public static final String JSON_PROPERTY_BLOCK_HASH = "blockHash";
  private String blockHash;

  public static final String JSON_PROPERTY_SIZE = "size";
  private Long size;

  public static final String JSON_PROPERTY_INPUT_COUNT = "inputCount";
  private Integer inputCount;

  public static final String JSON_PROPERTY_OUTPUT_COUNT = "outputCount";
  private Integer outputCount;

  public static final String JSON_PROPERTY_LOCK_TIME = "lockTime";
  private Long lockTime;

  public static final String JSON_PROPERTY_FEE = "fee";
  private Long fee;

  public static final String JSON_PROPERTY_CONFIRMATIONS = "confirmations";
  private Long confirmations;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Long timestamp;


  public BlockTx txid(String txid) {
    
    this.txid = txid;
    return this;
  }

   /**
   * Transaction hash.
   * @return txid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Transaction hash.")
  @JsonProperty(JSON_PROPERTY_TXID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTxid() {
    return txid;
  }


  public void setTxid(String txid) {
    this.txid = txid;
  }


  public BlockTx height(Long height) {
    
    this.height = height;
    return this;
  }

   /**
   * Block height of this tx.
   * @return height
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Block height of this tx.")
  @JsonProperty(JSON_PROPERTY_HEIGHT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getHeight() {
    return height;
  }


  public void setHeight(Long height) {
    this.height = height;
  }


  public BlockTx blockHash(String blockHash) {
    
    this.blockHash = blockHash;
    return this;
  }

   /**
   * Hash of the block
   * @return blockHash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Hash of the block")
  @JsonProperty(JSON_PROPERTY_BLOCK_HASH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getBlockHash() {
    return blockHash;
  }


  public void setBlockHash(String blockHash) {
    this.blockHash = blockHash;
  }


  public BlockTx size(Long size) {
    
    this.size = size;
    return this;
  }

   /**
   * transaction size
   * @return size
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "transaction size")
  @JsonProperty(JSON_PROPERTY_SIZE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getSize() {
    return size;
  }


  public void setSize(Long size) {
    this.size = size;
  }


  public BlockTx inputCount(Integer inputCount) {
    
    this.inputCount = inputCount;
    return this;
  }

   /**
   * Input count in this transaction
   * @return inputCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Input count in this transaction")
  @JsonProperty(JSON_PROPERTY_INPUT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getInputCount() {
    return inputCount;
  }


  public void setInputCount(Integer inputCount) {
    this.inputCount = inputCount;
  }


  public BlockTx outputCount(Integer outputCount) {
    
    this.outputCount = outputCount;
    return this;
  }

   /**
   * Output count in this transaction.
   * @return outputCount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Output count in this transaction.")
  @JsonProperty(JSON_PROPERTY_OUTPUT_COUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getOutputCount() {
    return outputCount;
  }


  public void setOutputCount(Integer outputCount) {
    this.outputCount = outputCount;
  }


  public BlockTx lockTime(Long lockTime) {
    
    this.lockTime = lockTime;
    return this;
  }

   /**
   * Lock time of this transaction
   * @return lockTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Lock time of this transaction")
  @JsonProperty(JSON_PROPERTY_LOCK_TIME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getLockTime() {
    return lockTime;
  }


  public void setLockTime(Long lockTime) {
    this.lockTime = lockTime;
  }


  public BlockTx fee(Long fee) {
    
    this.fee = fee;
    return this;
  }

   /**
   * Trasaction fee.
   * @return fee
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Trasaction fee.")
  @JsonProperty(JSON_PROPERTY_FEE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getFee() {
    return fee;
  }


  public void setFee(Long fee) {
    this.fee = fee;
  }


  public BlockTx confirmations(Long confirmations) {
    
    this.confirmations = confirmations;
    return this;
  }

   /**
   * Confirmations of this transaction, -1 if unconfirmed.
   * @return confirmations
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Confirmations of this transaction, -1 if unconfirmed.")
  @JsonProperty(JSON_PROPERTY_CONFIRMATIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getConfirmations() {
    return confirmations;
  }


  public void setConfirmations(Long confirmations) {
    this.confirmations = confirmations;
  }


  public BlockTx timestamp(Long timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Block timestamp for the transaction, confirmed tx only.
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Block timestamp for the transaction, confirmed tx only.")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockTx blockTx = (BlockTx) o;
    return Objects.equals(this.txid, blockTx.txid) &&
        Objects.equals(this.height, blockTx.height) &&
        Objects.equals(this.blockHash, blockTx.blockHash) &&
        Objects.equals(this.size, blockTx.size) &&
        Objects.equals(this.inputCount, blockTx.inputCount) &&
        Objects.equals(this.outputCount, blockTx.outputCount) &&
        Objects.equals(this.lockTime, blockTx.lockTime) &&
        Objects.equals(this.fee, blockTx.fee) &&
        Objects.equals(this.confirmations, blockTx.confirmations) &&
        Objects.equals(this.timestamp, blockTx.timestamp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txid, height, blockHash, size, inputCount, outputCount, lockTime, fee, confirmations, timestamp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockTx {\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    height: ").append(toIndentedString(height)).append("\n");
    sb.append("    blockHash: ").append(toIndentedString(blockHash)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    sb.append("    inputCount: ").append(toIndentedString(inputCount)).append("\n");
    sb.append("    outputCount: ").append(toIndentedString(outputCount)).append("\n");
    sb.append("    lockTime: ").append(toIndentedString(lockTime)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    confirmations: ").append(toIndentedString(confirmations)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

