/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.5
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Client public key result
 */
@ApiModel(description = "Client public key result")
@JsonPropertyOrder({
  ClientPubkeyResult.JSON_PROPERTY_PUBKEY,
  ClientPubkeyResult.JSON_PROPERTY_MESSAGE
})
@JsonTypeName("ClientPubkeyResult")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-06T11:49:07.594678+09:00[Asia/Tokyo]")
public class ClientPubkeyResult {
  public static final String JSON_PROPERTY_PUBKEY = "pubkey";
  private String pubkey;

  public static final String JSON_PROPERTY_MESSAGE = "message";
  private String message;


  public ClientPubkeyResult pubkey(String pubkey) {
    
    this.pubkey = pubkey;
    return this;
  }

   /**
   * return pubkey if created successfully
   * @return pubkey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return pubkey if created successfully")
  @JsonProperty(JSON_PROPERTY_PUBKEY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPubkey() {
    return pubkey;
  }


  public void setPubkey(String pubkey) {
    this.pubkey = pubkey;
  }


  public ClientPubkeyResult message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * return messages if broadcast failed
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return messages if broadcast failed")
  @JsonProperty(JSON_PROPERTY_MESSAGE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ClientPubkeyResult clientPubkeyResult = (ClientPubkeyResult) o;
    return Objects.equals(this.pubkey, clientPubkeyResult.pubkey) &&
        Objects.equals(this.message, clientPubkeyResult.message);
  }

  @Override
  public int hashCode() {
    return Objects.hash(pubkey, message);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ClientPubkeyResult {\n");
    sb.append("    pubkey: ").append(toIndentedString(pubkey)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

