/*
 * MicrovisionChain API Document
 * API definition for MicrovisionChain provided apis
 *
 * The version of the OpenAPI document: 3.0.8
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.metasv.mvc.client.openapi.model.InvalidBroadcastCollide;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Invalid transactions detected during validation (if there are any)
 */
@ApiModel(description = "Invalid transactions detected during validation (if there are any)")
@JsonPropertyOrder({
  InvalidBroadCast.JSON_PROPERTY_TXID,
  InvalidBroadCast.JSON_PROPERTY_REJECT_CODE,
  InvalidBroadCast.JSON_PROPERTY_REJECT_REASON,
  InvalidBroadCast.JSON_PROPERTY_COLLIDE_WITH
})
@JsonTypeName("InvalidBroadCast")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-16T17:24:50.047362+09:00[Asia/Tokyo]")
public class InvalidBroadCast {
  public static final String JSON_PROPERTY_TXID = "txid";
  private String txid;

  public static final String JSON_PROPERTY_REJECT_CODE = "reject_code";
  private Integer rejectCode;

  public static final String JSON_PROPERTY_REJECT_REASON = "reject_reason";
  private String rejectReason;

  public static final String JSON_PROPERTY_COLLIDE_WITH = "collideWith";
  private List<InvalidBroadcastCollide> collideWith = null;


  public InvalidBroadCast txid(String txid) {
    
    this.txid = txid;
    return this;
  }

   /**
   * return txid if broadcast success
   * @return txid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return txid if broadcast success")
  @JsonProperty(JSON_PROPERTY_TXID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTxid() {
    return txid;
  }


  public void setTxid(String txid) {
    this.txid = txid;
  }


  public InvalidBroadCast rejectCode(Integer rejectCode) {
    
    this.rejectCode = rejectCode;
    return this;
  }

   /**
   * return messages if broadcast failed
   * @return rejectCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return messages if broadcast failed")
  @JsonProperty(JSON_PROPERTY_REJECT_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getRejectCode() {
    return rejectCode;
  }


  public void setRejectCode(Integer rejectCode) {
    this.rejectCode = rejectCode;
  }


  public InvalidBroadCast rejectReason(String rejectReason) {
    
    this.rejectReason = rejectReason;
    return this;
  }

   /**
   * return messages if broadcast failed
   * @return rejectReason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return messages if broadcast failed")
  @JsonProperty(JSON_PROPERTY_REJECT_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getRejectReason() {
    return rejectReason;
  }


  public void setRejectReason(String rejectReason) {
    this.rejectReason = rejectReason;
  }


  public InvalidBroadCast collideWith(List<InvalidBroadcastCollide> collideWith) {
    
    this.collideWith = collideWith;
    return this;
  }

  public InvalidBroadCast addCollideWithItem(InvalidBroadcastCollide collideWithItem) {
    if (this.collideWith == null) {
      this.collideWith = new ArrayList<>();
    }
    this.collideWith.add(collideWithItem);
    return this;
  }

   /**
   * return messages if broadcast failed
   * @return collideWith
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "return messages if broadcast failed")
  @JsonProperty(JSON_PROPERTY_COLLIDE_WITH)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<InvalidBroadcastCollide> getCollideWith() {
    return collideWith;
  }


  public void setCollideWith(List<InvalidBroadcastCollide> collideWith) {
    this.collideWith = collideWith;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InvalidBroadCast invalidBroadCast = (InvalidBroadCast) o;
    return Objects.equals(this.txid, invalidBroadCast.txid) &&
        Objects.equals(this.rejectCode, invalidBroadCast.rejectCode) &&
        Objects.equals(this.rejectReason, invalidBroadCast.rejectReason) &&
        Objects.equals(this.collideWith, invalidBroadCast.collideWith);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txid, rejectCode, rejectReason, collideWith);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InvalidBroadCast {\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    rejectCode: ").append(toIndentedString(rejectCode)).append("\n");
    sb.append("    rejectReason: ").append(toIndentedString(rejectReason)).append("\n");
    sb.append("    collideWith: ").append(toIndentedString(collideWith)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

