/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * treasury transaction history
 */
@ApiModel(description = "treasury transaction history")
@JsonPropertyOrder({
  TreasuryHistory.JSON_PROPERTY_TXID,
  TreasuryHistory.JSON_PROPERTY_OUTCOME,
  TreasuryHistory.JSON_PROPERTY_TIMESTAMP,
  TreasuryHistory.JSON_PROPERTY_REASON,
  TreasuryHistory.JSON_PROPERTY_ANNOUNCEMENT_URL
})
@JsonTypeName("TreasuryHistory")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-06T11:46:13.148624+09:00[Asia/Tokyo]")
public class TreasuryHistory {
  public static final String JSON_PROPERTY_TXID = "txid";
  private String txid;

  public static final String JSON_PROPERTY_OUTCOME = "outcome";
  private Long outcome;

  public static final String JSON_PROPERTY_TIMESTAMP = "timestamp";
  private Long timestamp;

  public static final String JSON_PROPERTY_REASON = "reason";
  private String reason;

  public static final String JSON_PROPERTY_ANNOUNCEMENT_URL = "announcementUrl";
  private String announcementUrl;


  public TreasuryHistory txid(String txid) {
    
    this.txid = txid;
    return this;
  }

   /**
   * treasury transaction txid.
   * @return txid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "treasury transaction txid.")
  @JsonProperty(JSON_PROPERTY_TXID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTxid() {
    return txid;
  }


  public void setTxid(String txid) {
    this.txid = txid;
  }


  public TreasuryHistory outcome(Long outcome) {
    
    this.outcome = outcome;
    return this;
  }

   /**
   * treasury transaction spent outcome in satoshi.
   * @return outcome
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "treasury transaction spent outcome in satoshi.")
  @JsonProperty(JSON_PROPERTY_OUTCOME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getOutcome() {
    return outcome;
  }


  public void setOutcome(Long outcome) {
    this.outcome = outcome;
  }


  public TreasuryHistory timestamp(Long timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * treasury transaction timestamp.
   * @return timestamp
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "treasury transaction timestamp.")
  @JsonProperty(JSON_PROPERTY_TIMESTAMP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(Long timestamp) {
    this.timestamp = timestamp;
  }


  public TreasuryHistory reason(String reason) {
    
    this.reason = reason;
    return this;
  }

   /**
   * Reason for treasury transaction.
   * @return reason
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Reason for treasury transaction.")
  @JsonProperty(JSON_PROPERTY_REASON)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getReason() {
    return reason;
  }


  public void setReason(String reason) {
    this.reason = reason;
  }


  public TreasuryHistory announcementUrl(String announcementUrl) {
    
    this.announcementUrl = announcementUrl;
    return this;
  }

   /**
   * Announcement link for treasury transaction.
   * @return announcementUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Announcement link for treasury transaction.")
  @JsonProperty(JSON_PROPERTY_ANNOUNCEMENT_URL)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAnnouncementUrl() {
    return announcementUrl;
  }


  public void setAnnouncementUrl(String announcementUrl) {
    this.announcementUrl = announcementUrl;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TreasuryHistory treasuryHistory = (TreasuryHistory) o;
    return Objects.equals(this.txid, treasuryHistory.txid) &&
        Objects.equals(this.outcome, treasuryHistory.outcome) &&
        Objects.equals(this.timestamp, treasuryHistory.timestamp) &&
        Objects.equals(this.reason, treasuryHistory.reason) &&
        Objects.equals(this.announcementUrl, treasuryHistory.announcementUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(txid, outcome, timestamp, reason, announcementUrl);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TreasuryHistory {\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    outcome: ").append(toIndentedString(outcome)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    reason: ").append(toIndentedString(reason)).append("\n");
    sb.append("    announcementUrl: ").append(toIndentedString(announcementUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

