/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Parsed inputs from raw tx. Use output api to get value and spent info.
 */
@ApiModel(description = "Parsed inputs from raw tx. Use output api to get value and spent info.")
@JsonPropertyOrder({
  TxInput.JSON_PROPERTY_INDEX,
  TxInput.JSON_PROPERTY_UTXO_TXID,
  TxInput.JSON_PROPERTY_UTXO_INDEX,
  TxInput.JSON_PROPERTY_ADDRESS,
  TxInput.JSON_PROPERTY_VALUE,
  TxInput.JSON_PROPERTY_UNLOCK_SCRIPT
})
@JsonTypeName("TxInput")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-06T11:46:13.148624+09:00[Asia/Tokyo]")
public class TxInput {
  public static final String JSON_PROPERTY_INDEX = "index";
  private Integer index;

  public static final String JSON_PROPERTY_UTXO_TXID = "utxoTxid";
  private String utxoTxid;

  public static final String JSON_PROPERTY_UTXO_INDEX = "utxoIndex";
  private Integer utxoIndex;

  public static final String JSON_PROPERTY_ADDRESS = "address";
  private String address;

  public static final String JSON_PROPERTY_VALUE = "value";
  private Long value;

  public static final String JSON_PROPERTY_UNLOCK_SCRIPT = "unlockScript";
  private String unlockScript;


  public TxInput index(Integer index) {
    
    this.index = index;
    return this;
  }

   /**
   * Input index of the tx.
   * @return index
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Input index of the tx.")
  @JsonProperty(JSON_PROPERTY_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getIndex() {
    return index;
  }


  public void setIndex(Integer index) {
    this.index = index;
  }


  public TxInput utxoTxid(String utxoTxid) {
    
    this.utxoTxid = utxoTxid;
    return this;
  }

   /**
   * The outpoint utxo txid that this input spent
   * @return utxoTxid
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The outpoint utxo txid that this input spent")
  @JsonProperty(JSON_PROPERTY_UTXO_TXID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUtxoTxid() {
    return utxoTxid;
  }


  public void setUtxoTxid(String utxoTxid) {
    this.utxoTxid = utxoTxid;
  }


  public TxInput utxoIndex(Integer utxoIndex) {
    
    this.utxoIndex = utxoIndex;
    return this;
  }

   /**
   * The outpoint utxo index that this input spent
   * @return utxoIndex
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The outpoint utxo index that this input spent")
  @JsonProperty(JSON_PROPERTY_UTXO_INDEX)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getUtxoIndex() {
    return utxoIndex;
  }


  public void setUtxoIndex(Integer utxoIndex) {
    this.utxoIndex = utxoIndex;
  }


  public TxInput address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * Parsed address from pubkey(P2PKH input only).
   * @return address
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Parsed address from pubkey(P2PKH input only).")
  @JsonProperty(JSON_PROPERTY_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public TxInput value(Long value) {
    
    this.value = value;
    return this;
  }

   /**
   * satoshi value of this input.
   * @return value
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "satoshi value of this input.")
  @JsonProperty(JSON_PROPERTY_VALUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getValue() {
    return value;
  }


  public void setValue(Long value) {
    this.value = value;
  }


  public TxInput unlockScript(String unlockScript) {
    
    this.unlockScript = unlockScript;
    return this;
  }

   /**
   * The hex of the input script.
   * @return unlockScript
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The hex of the input script.")
  @JsonProperty(JSON_PROPERTY_UNLOCK_SCRIPT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUnlockScript() {
    return unlockScript;
  }


  public void setUnlockScript(String unlockScript) {
    this.unlockScript = unlockScript;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TxInput txInput = (TxInput) o;
    return Objects.equals(this.index, txInput.index) &&
        Objects.equals(this.utxoTxid, txInput.utxoTxid) &&
        Objects.equals(this.utxoIndex, txInput.utxoIndex) &&
        Objects.equals(this.address, txInput.address) &&
        Objects.equals(this.value, txInput.value) &&
        Objects.equals(this.unlockScript, txInput.unlockScript);
  }

  @Override
  public int hashCode() {
    return Objects.hash(index, utxoTxid, utxoIndex, address, value, unlockScript);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TxInput {\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    utxoTxid: ").append(toIndentedString(utxoTxid)).append("\n");
    sb.append("    utxoIndex: ").append(toIndentedString(utxoIndex)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    unlockScript: ").append(toIndentedString(unlockScript)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

