/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.7
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.ArrayList;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * Request object to batch pick utxo
 */
@ApiModel(description = "Request object to batch pick utxo")
@JsonPropertyOrder({
  UtxoPickRequest.JSON_PROPERTY_ADDRESSES,
  UtxoPickRequest.JSON_PROPERTY_AMOUNT
})
@JsonTypeName("UtxoPickRequest")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-04-16T16:52:15.815523+09:00[Asia/Tokyo]")
public class UtxoPickRequest {
  public static final String JSON_PROPERTY_ADDRESSES = "addresses";
  private List<String> addresses = null;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  private Long amount;


  public UtxoPickRequest addresses(List<String> addresses) {
    
    this.addresses = addresses;
    return this;
  }

  public UtxoPickRequest addAddressesItem(String addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * The address list to pick utxo from
   * @return addresses
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The address list to pick utxo from")
  @JsonProperty(JSON_PROPERTY_ADDRESSES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<String> getAddresses() {
    return addresses;
  }


  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }


  public UtxoPickRequest amount(Long amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * The total amount you want to pick
   * @return amount
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The total amount you want to pick")
  @JsonProperty(JSON_PROPERTY_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Long getAmount() {
    return amount;
  }


  public void setAmount(Long amount) {
    this.amount = amount;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UtxoPickRequest utxoPickRequest = (UtxoPickRequest) o;
    return Objects.equals(this.addresses, utxoPickRequest.addresses) &&
        Objects.equals(this.amount, utxoPickRequest.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, amount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UtxoPickRequest {\n");
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

