/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.1
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.api;

import com.metasv.mvc.client.openapi.ApiException;
import com.metasv.mvc.client.openapi.model.AddressBalance;
import com.metasv.mvc.client.openapi.model.AddressTx;
import com.metasv.mvc.client.openapi.model.AddressUtxo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AddressApi
 */
@Ignore
public class AddressApiTest {

    private final AddressApi api = new AddressApi();

    
    /**
     * Get address balance by specific address.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addressAddressBalanceGetTest() throws ApiException {
        String address = null;
        AddressBalance response = api.addressAddressBalanceGet(address);

        // TODO: test validations
    }
    
    /**
     * Get address history by specific address(recent 10 days available).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addressAddressTxGetTest() throws ApiException {
        String address = null;
        String flag = null;
        Boolean confirmed = null;
        List<AddressTx> response = api.addressAddressTxGet(address, flag, confirmed);

        // TODO: test validations
    }
    
    /**
     * Get address utxos by specific address(100 per page).
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void addressAddressUtxoGetTest() throws ApiException {
        String address = null;
        String flag = null;
        List<AddressUtxo> response = api.addressAddressUtxoGet(address, flag);

        // TODO: test validations
    }
    
}
