/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.api;

import com.metasv.mvc.client.openapi.model.BlockHeaderIndex;
import com.metasv.mvc.client.openapi.model.BlockHeaderPage;
import com.metasv.mvc.client.openapi.model.BlockchainInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlockApi
 */
@Ignore
public class BlockApiTest {

    private final BlockApi api = new BlockApi();

    
    /**
     * Get block request by height or hash
     *
     * 
     */
    @Test
    public void blockBlockIdGetTest()  {
        String blockId = null;
        BlockHeaderIndex response = api.blockBlockIdGet(blockId).block();

        // TODO: test validations
    }
    
    /**
     * Get recent block list by paging. 30 items per page.
     *
     * 
     */
    @Test
    public void blockGetTest()  {
        Long last = null;
        List<BlockHeaderPage> response = api.blockGet(last).collectList().block();

        // TODO: test validations
    }
    
    /**
     * Get current blockchain info from full node.
     *
     * 
     */
    @Test
    public void blockInfoGetTest()  {
        BlockchainInfo response = api.blockInfoGet().block();

        // TODO: test validations
    }
    
}
