/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.api;

import com.metasv.mvc.client.openapi.ApiException;
import com.metasv.mvc.client.openapi.model.TreasuryHistory;
import com.metasv.mvc.client.openapi.model.TreasuryInfo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TreasuryApi
 */
@Ignore
public class TreasuryApiTest {

    private final TreasuryApi api = new TreasuryApi();

    
    /**
     * Get current treasury info.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void treasuryGetTest() throws ApiException {
        TreasuryInfo response = api.treasuryGet();

        // TODO: test validations
    }
    
    /**
     * Get all treasury history.
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void treasuryHistoryGetTest() throws ApiException {
        List<TreasuryHistory> response = api.treasuryHistoryGet();

        // TODO: test validations
    }
    
}
