/*
 * MetaSV for MVC API Spec
 * API definition for MetaSV provided apis
 *
 * The version of the OpenAPI document: 3.0.4
 * Contact: heqiming@metasv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.metasv.mvc.client.openapi.api;

import com.metasv.mvc.client.openapi.model.ErrorResponse;
import com.metasv.mvc.client.openapi.model.XpubAddress;
import com.metasv.mvc.client.openapi.model.XpubLiteBalance;
import com.metasv.mvc.client.openapi.model.XpubUtxo;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for XpubApi
 */
@Ignore
public class XpubApiTest {

    private final XpubApi api = new XpubApi();

    
    /**
     * Get xpub address type and index. Only index under /0/70 /1/30 is valid. Otherwise not found.
     *
     * 
     */
    @Test
    public void xpubLiteXpubAddressAddressGetTest()  {
        String xpub = null;
        String address = null;
        XpubAddress response = api.xpubLiteXpubAddressAddressGet(xpub, address).block();

        // TODO: test validations
    }
    
    /**
     * Get xpub balances including confirmed and unconfirmed.
     *
     * This api returns confirmed balance(same as address balance), not sumed utxos.
     */
    @Test
    public void xpubLiteXpubBalanceGetTest()  {
        String xpub = null;
        XpubLiteBalance response = api.xpubLiteXpubBalanceGet(xpub).block();

        // TODO: test validations
    }
    
    /**
     * Get xpub utxos by specific xpub(300 per page).
     *
     * 
     */
    @Test
    public void xpubLiteXpubUtxoGetTest()  {
        String xpub = null;
        Integer limit = null;
        List<XpubUtxo> response = api.xpubLiteXpubUtxoGet(xpub, limit).collectList().block();

        // TODO: test validations
    }
    
}
